name: qmllib_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - copy
  - ctypes
  - jupytext
  - monkeytype
  - numpy
  - numpy
  - openbabel
  - pandas
  - pip
  - pre-commit
  - pybel
  - pytest
  - scipy
