name: qmllib_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - jupytext
  - monkeytype
  - numpy
  - openbabel
  - pandas
  - pip
  - pre-commit
  - pytest
  - scikit-learn
  - scipy
  - pip:
     - pybel
