name: qmllib_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - jupytext
  - monkeytype
  - numpy
  - pandas
  - pyarrow
  - pip
  - pre-commit
  - pytest
  - scikit-learn
  - scipy
  # build
  - meson
  - ninja
