name: qmllib_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - pip
  - pip:
    - jupytext
    - monkeytype
    - numpy
    - pandas
    - pandas
    - pre-commit
    - pyarrow
    - pytest
    - scikit-learn
    - scipy
    # build
    - build
    - meson
    - ninja
    # publish
    - twine
