import numpy
import numpy.typing
import typing
from . import ffchl_kernel_types as ffchl_kernel_types

def fget_atomic_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    x2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_atomic_local_gradient_5point_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    x2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    n2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    nm2: typing.SupportsInt,
    na1: typing.SupportsInt,
    naq2: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    dx: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_atomic_local_gradient_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    x2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    n2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    nm2: typing.SupportsInt,
    na1: typing.SupportsInt,
    naq2: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    dx: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_atomic_local_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    x2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    n2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    nm2: typing.SupportsInt,
    na1: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_atomic_symmetric_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_force_alphas_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    x2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    forces: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    energies: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    n2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    nm2: typing.SupportsInt,
    na1: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    dx: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    llambda: typing.SupportsFloat,
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_gaussian_process_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    x2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    n2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    nm2: typing.SupportsInt,
    naq2: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    dx: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_global_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    x2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    n2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    nm2: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_global_symmetric_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    x2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    n2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    nm2: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_local_gradient_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    x2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    n2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    nm2: typing.SupportsInt,
    naq2: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    dx: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_local_hessian_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    x2: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    n2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh2: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    nm2: typing.SupportsInt,
    naq1: typing.SupportsInt,
    naq2: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    dx: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_local_symmetric_hessian_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    naq1: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    dx: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
def fget_symmetric_kernels_fchl(
    x1: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    verbose: bool,
    n1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nneigh1: typing.Annotated[numpy.typing.ArrayLike, numpy.int32],
    nm1: typing.SupportsInt,
    nsigmas: typing.SupportsInt,
    t_width: typing.SupportsFloat,
    d_width: typing.SupportsFloat,
    cut_start: typing.SupportsFloat,
    cut_distance: typing.SupportsFloat,
    order: typing.SupportsInt,
    pd: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
    distance_scale: typing.SupportsFloat,
    angular_scale: typing.SupportsFloat,
    alchemy: bool,
    two_body_power: typing.SupportsFloat,
    three_body_power: typing.SupportsFloat,
    kernel_idx: typing.SupportsInt,
    parameters: typing.Annotated[numpy.typing.ArrayLike, numpy.float64],
) -> numpy.typing.NDArray[numpy.float64]: ...
