
name: Test Python package

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Testing
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: dev
          environment-file: ./environment_dev.yaml
          python-version: ${{ matrix.python-version }}
      - run: |
          ls
          pwd
          which python
          conda info
      - run: make compile python=python
      - run: pip install -e .
      - run: make test python=python
      - run: make format python=python
